<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>46896f2d-0d08-42e6-819d-c15919c4f949</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://login.xero.com/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-tertiary-alt global-ceiling-bar-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Login
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js cors localstorage sessionstorage csspointerevents preserve3d supports no-touchevents flexbox flexboxlegacy no-flexboxtweener csstransforms3d csstransitions&quot;]/body[@class=&quot;xero is-live-mode&quot;]/div[5]/header[1]/nav[1]/div[@class=&quot;global-header&quot;]/div[@class=&quot;global-hamburger-content-wrapper&quot;]/div[@class=&quot;global-ceiling-bar&quot;]/div[@class=&quot;global-ceiling-bar-row&quot;]/div[@class=&quot;global-ceiling-bar-group&quot;]/ul[@class=&quot;global-ceiling-bar-nav&quot;]/li[@class=&quot;global-ceiling-bar-cta1&quot;]/a[@class=&quot;btn btn-tertiary-alt global-ceiling-bar-btn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
